---
site_name: My Docs
site_author: "Emmmanuel Roux"
theme:
  name: "material"
  custom_dir: theme/
  logo : images/logo.svg
  icon:
    # logo: images/logo.svg
    favicon: images/favicon.png
  features:
    - tabs
    # The (still experimental) instant loading feature will intercept clicks
    # on all internal links and dispatch them directly via XHR without a full
    # page reload.
    - instant
  palette:
    primary: "indigo"
    accent: "lime"

nav:
  - Home: index.md
  - doc:
      - Markdown: doc/md.md
  - Python:
      - Intro: _nb/=Py/01_Python/01 - Python - CPython design.ipynb
      - Typing: Python/typing.md
      - Envs: Python/envs.md
      - "Iterators, generators and coroutines": Python/IterGen.md
      - Tests: Python/test.md
      - Ubuntu: shell/Ubuntu/python.md
  - DevOps:
      - Ansible: devops/ansible.md
      - "Code coverage": devops/codecov.md
  - Shell:
      - Intro: shell/intro.md
      - zsh: shell/zsh.md
      - vim: shell/vim.md
      - git: shell/git.md
      - fzf: shell/fzf.md
      - Ubuntu:
          - Configuration: shell/Ubuntu/configuration.md
          - Python: shell/Ubuntu/python.md
      - helpers: shell/sys.md
  - DB:
      - intro: DB/intro.md
      - MongoDB:
          - Intro: DB/mongoDB/_intro.md
          - "Aggregation framework": DB/mongoDB/Aggregation.md
      - SQL:
          - PostgreSQL: DB/SQL/postgres.md
      - "Object store":
          - Intro: DB/S3/_intro.md
  - Data:
      - Intro: data/_intro.md
      - ndarray:
          - Intro: ndarray/intro.md
      - "Time series":
          - "Intro": data/timeseries/_intro.md
          - "Features selection": data/timeseries/features.md
          - "Matrix profile": data/timeseries/matrixprofile.md
          - "Windowing": data/windowing.md
      - "Machine Learning":
          - Time series: ml/dl.md
  - Visualization:
    - Matplolib: Viz/matplotlib.md
  - WebDev:
      - Intro: WebDev/Intro.md
      - CSS: WebDev/css.md
      - node: WebDev/node.md
      - REACT: WebDev/REACT.md

plugins:
  - mknotebooks
  - exclude:
      glob:
        - _nb/extern/*
  - awesome-pages
  - search

markdown_extensions:
  # Admonition is an extension included in the standard Markdown library that
  # makes it possible to add block-styled side content
  # https://squidfunk.github.io/mkdocs-material/extensions/admonition/
  - admonition
  # Adds the ability to add inline footnotes to your documentation
  # https://squidfunk.github.io/mkdocs-material/extensions/footnotes/
  - footnotes
  # ########################################################################
  # PyMdown Extensions
  # https://squidfunk.github.io/mkdocs-material/extensions/pymdown/
  # ======   https://facelessuser.github.io/pymdown-extensions/   ======== #
  # ########################################################################
  # Arithmatex is an extension that preserves LaTeX math equations
  # during the Markdown conversion process so that they can be used with
  # MathJax.
  - pymdownx.arithmatex
  # BetterEm is a different approach to emphasis than Python Markdown's
  # default. It works similar but handles certain corner cases differently.
  - pymdownx.betterem:
      smart_enable: asterisk
  # Caret is an extension that is syntactically built around the ^ character.
  # It adds support for inserting superscripts and adds an easy way to place
  # text in an <ins> tag.
  - pymdownx.caret
  # Details is an extension that creates collapsible elements that hide their
  # content. It uses the HTML5 <details><summary> tags to accomplish this. It
  # supports nesting and you can also force the default state to be open. And
  # if you want to style some different than others, you can optionally feed
  # in a custom class.
  - pymdownx.details
  # PyMdown Extensions' extra is just like Python Markdown's extra except
  # smartstrong is replaced by betterem and fenced_code is replaced by
  # superfences
  - pymdownx.extra
  # InlineHilite is an inline code highlighter
  - pymdownx.inlinehilite
  # Mark adds the ability to insert <mark></mark> tags,e.g  ==Mark===
  - pymdownx.mark
  # SmartSymbols adds syntax for creating special characters such as
  # trademarks, arrows, fractions, etc.
  - pymdownx.smartsymbols
  # Snippets is an extension to insert markdown or HTML snippets into another
  # markdown file.
  - pymdownx.snippets
  # - pymdownx.superfences:
  #     preserve_tabs: true
  #     custom_fences:
  #       - name: flow
  #         class: uml-flowchart
  #         format: !!python/name:pymdownx.superfences.fence_code_format
  #       - name: sequence
  #         class: uml-sequence-diagram
  #         format: !!python/name:pymdownx.superfences.fence_code_format
  #       - name: treediagram
  #         class: uml-treediagram
  #         format: !!python/name:pymdownx.superfences.fence_code_format
  # To denote a subscript, you can surround the desired content in single ~
  - pymdownx.tilde
  - toc:
      permalink: True

site_url: "https://github.com/fesaille"
remote_branch: master
# repo_name: 'gwin-zegal.github.io'
# repo_url: 'https://github.com/fesaille'

extra_css:
  - "_css/extra.css"
  - "https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css"
  - "https://fonts.googleapis.com/icon?family=Material+Icons"

extra_javascript:
  - _js/extra.js
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML"
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML"
  - "https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.min.js"
  - "https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"
  - "https://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.6/sequence-diagram-min.js"
  - "https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.6.5/flowchart.min.js"
  - "https://cdnjs.cloudflare.com/ajax/libs/treant-js/1.0/Treant.min.js"
  - "https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"
#extra:
#  social:
#    - type: 'github'
#      link: 'https://github.com/fesaille'
