---
site_name: My Docs
site_author: "Emmmanuel Roux"
theme:
  name: "material"
  custom_dir: theme/
  font:
    text: Work Sans
  logo: images/logo.svg
  icon:
    # logo: images/logo.svg
    favicon: images/favicon.png
  features:
    - tabs
    # The (still experimental) instant loading feature will intercept clicks
    # on all internal links and dispatch them directly via XHR without a full
    # page reload.
    - instant
  palette:
    primary: "indigo"
    accent: "lime"

nav:
  - Home: index.md
  - Linux: 
      - shell: shell/intro.md
      - zsh: shell/zsh.md
      - tmux: shell/tmux.md
      - vim:
          - Intro: shell/vim.md
          - Panes: shell/vim/panes.md
          - Edition: shell/vim/edition.md
          - Search: shell/vim/search.md
          - Motion: shell/vim/motion.md
          - Plugins: shell/vim/plugins.md
          - Script: shell/vim/script.md
          - "Language support": shell/vim/languages.md
      - freedesktop: linux/freedesktop.md
      - network: linux/network.md
      - Ubuntu:
          - Configuration: shell/Ubuntu/configuration.md
          - Python: shell/Ubuntu/python.md
  - "SW dvpt":
      - VCS:
          - git: sw_dvpt/git.md
      - "CI/CD":
          - Intro: sw_dvpt/ci_cd/cicd.md
          - "Code coverage": sw_dvpt/ci_cd/codecov.md
      - "Design patterns": sw_dvpt/patterns.md
  - Infrastructure:
      - VM: infrastructure/vm.md
      - DevOps:
          - Ansible: infrastructure/devops/ansible.md
      - Containerization:
          - Docker: infrastructure/containerization/intro.md
          - Containerd: infrastructure/containerization/containerd.md
          - Docker CLI: infrastructure/containerization/cli.md
          - Images:
              - MongoDB: data/db/mongoDB/docker.md
      - Orchestration:
          - Intro: infrastructure/orchestration/intro.md
          - CLI usage: infrastructure/orchestration/cli.md
          - "K8S distributions": infrastructure/orchestration/k8sdist.md
  - Cloud:
      - "Cloud native": cloud/cloudnative.md
      - "Cloud landscape": cloud/cloudlandscape.md
  - Data:
      - "CRISP-DM": data/crisp-dm.md 
      - intake: Catalogize.ipynb
      - intake2: data/Covid.ipynb
      - Pipelines:
          - Luigi: data/pipelines/luigi.md
          - prefect: data/pipelines/prefect.md
      - Visualization:
          - Matplolib: data/viz/matplotlib.md
      - intro: data/db/intro.md
      - SQL:
          - Intro: data/db/SQL/_intro.md
          - PostgreSQL: data/db/SQL/postgres.md
      - "Object store":
          - Intro: data/db/S3/_intro.md
      - MongoDB:
          - Intro: data/db/mongoDB/_intro.md
          - Docker Image: data/db/mongoDB/docker.md
          - "Aggregation framework": data/db/mongoDB/Aggregation.md
  - "AI/ML":
      - Intro: ml/data.md
      - ndarray:
          - Intro: ml/ndarray/intro.md
      - Features: ml/features.md
      - "Time series":
          - "Intro": ml/timeseries/_intro.md
          - "Matrix profile": ml/timeseries/matrixprofile.md
          - "Windowing": ml/windowing.md
      - Descriptive statistics: ml/descriptivestatistics.md
      - Bayesian inference: ml/bayesianinference.md
      - Regression: ml/regression.md
      - Pipelining: ml/pipelines.md
  - Python:
      # - Intro: "_nb/=Py/01_Python/01 - Python - CPython design.ipynb"
      - Environments: Python/env.md
      - Typing: Python/typing.md
      - "Iterators, generators and coroutines": Python/IterGen.md
      - ASyncio: Python/asyncio.md
      - Tests: Python/test.md
      - Click: Python/click.md
      - Profiling: Python/profiling.md
  - Go:
      - Concurency: go/concurency.md
      - Distributed: go/distributed.md
  - WebDev:
      - Intro: WebDev/Intro.md
      - CSS: WebDev/css.md
      - node: WebDev/node.md
      - REACT: WebDev/REACT.md
  - "?":
      - Help: doc/md.md
      - "MD: basic": extern/md-guide/basic-syntax.md
      - "MD: extended": extern/md-guide/extended-syntax.md

plugins:
  - mknotebooks:
       enable_default_jupyter_cell_styling: false
  - exclude:
      glob:
        - _nb/*
        - _nb/extern/*
  - awesome-pages
  - search

markdown_extensions:
  # Admonition is an extension included in the standard Markdown library that
  # makes it possible to add block-styled side content
  # https://squidfunk.github.io/mkdocs-material/extensions/admonition/
  - admonition
  # Adds the ability to add inline footnotes to your documentation
  # https://squidfunk.github.io/mkdocs-material/extensions/footnotes/
  - footnotes
  - md_in_html
  - meta
  # ########################################################################
  # PyMdown Extensions
  # https://squidfunk.github.io/mkdocs-material/extensions/pymdown/
  # ======   https://facelessuser.github.io/pymdown-extensions/   ======== #
  # ########################################################################
  # Arithmatex is an extension that preserves LaTeX math equations
  # during the Markdown conversion process so that they can be used with
  # MathJax.
  - pymdownx.arithmatex
  # BetterEm is a different approach to emphasis than Python Markdown's
  # default. It works similar but handles certain corner cases differently.
  - pymdownx.betterem:
      smart_enable: asterisk
  # Caret is an extension that is syntactically built around the ^ character.
  # It adds support for inserting superscripts and adds an easy way to place
  # text in an <ins> tag.
  - pymdownx.caret
  # Details is an extension that creates collapsible elements that hide their
  # content. It uses the HTML5 <details><summary> tags to accomplish this. It
  # supports nesting and you can also force the default state to be open. And
  # if you want to style some different than others, you can optionally feed
  # in a custom class.
  - pymdownx.details
  # PyMdown Extensions' extra is just like Python Markdown's extra except
  # smartstrong is replaced by betterem and fenced_code is replaced by
  # superfences
  - pymdownx.extra
  # InlineHilite is an inline code highlighter
  - pymdownx.inlinehilite
  # Mark adds the ability to insert <mark></mark> tags,e.g  ==Mark===
  - pymdownx.mark
  # SmartSymbols adds syntax for creating special characters such as
  # trademarks, arrows, fractions, etc.
  - pymdownx.smartsymbols
  # Snippets is an extension to insert markdown or HTML snippets into another
  # markdown file.
  - pymdownx.snippets
  - pymdownx.superfences
  #     preserve_tabs: true
  #     custom_fences:
  #       - name: flow
  #         class: uml-flowchart
  #         format: !!python/name:pymdownx.superfences.fence_code_format
  #       - name: sequence
  #         class: uml-sequence-diagram
  #         format: !!python/name:pymdownx.superfences.fence_code_format
  #       - name: treediagram
  #         class: uml-treediagram
  #         format: !!python/name:pymdownx.superfences.fence_code_format
  # To denote a subscript, you can surround the desired content in single ~
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.keys
  - toc:
      permalink: True

site_url: "https://github.com/fesaille"
remote_branch: master
# repo_name: 'gwin-zegal.github.io'
# repo_url: 'https://github.com/fesaille'

extra_css:
  - "_css/extra.css"
  - "https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css"
  - "https://fonts.googleapis.com/icon?family=Material+Icons"

extra_javascript:
  - _js/extra.js
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML"
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML"
  - "https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.min.js"
  - "https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"
  - "https://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.6/sequence-diagram-min.js"
  - "https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.6.5/flowchart.min.js"
  - "https://cdnjs.cloudflare.com/ajax/libs/treant-js/1.0/Treant.min.js"
  - "https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"
#extra:
#  social:
#    - type: 'github'
#      link: 'https://github.com/fesaille'
